language: java
sudo: false
script: mvn install

before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "swalana"
      - git config --local user.email "sara.ott@lernende.bbw.ch"
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - git tag $TRAVIS_TAG
    deploy:
      provider: releases
      api_key: "GITHUB OAUTH TOKEN"
      file: "FILE TO UPLOAD"
      skip_cleanup: true
